### PR TITLE
Gemify!

### PR DESCRIPTION
**Pull request by asmith-mdsol**
This change makes installation and use easier, especially in the context of another project, which is precisely what I'm going to need for the repo/PR audit tool.

Calling potentials users @byoung, @isaacwong, @glow-mdsol, @chad-medi for help in reviewing and merging. (Feel we need a German style compound noun for "review and merge" although I've always been partial to "landing".)

### CODE REVIEW

**Comment by byoung** [comment]
Review = Bewertung
Merge = Verschmelzen

How about Bewerschmelzen == assessment melting

**Comment by byoung** [comment]
Wertung == rating

**Comment by byoung** [comment]
Sieht gut aus, sind vorbei specs - Verschmelzung

```
> rspec spec
Run options: include {:focus=>true}

All examples were filtered out; ignoring {:focus=>true}
....................................GitHub login: GitHub password: .............................................

Finished in 5.79 seconds
81 examples, 0 failures

Randomized with seed 29932

```

**Comment by asmith-mdsol** [comment]
Vielen dank @byoung!

**Pull request merged**
